[phases.setup]
nixpkgsArchive = "25f2aaa926f81aaf03398a2364b61fac2df38dd4"

[phases.install]
cmds = [
  "npm install -g corepack@latest",
  "corepack enable",
  "corepack prepare pnpm@11.4.0 --activate",
  "pnpm install --frozen-lockfile",
]
